### ISSUE TITLE
support pyspark

### ISSUE THREAD

**Issue by ARashitov** [opensearch-project/opensearch-hadoop#166] opened 2023-04-02 12:37 UTC
### Is your feature request related to a problem?
Documentation mentions: OpenSearch-Hadoop provides native (Java and Scala) integration with Spark. Is there python support in plan? Or is it possible to use ElasticSearch with stack: `python3`, `pyspark=3.3.0` and `opensearch=1.3.8`?

### What solution would you like?
Support python language for spark

**Comment by harshavamsi** [comment] 2023-04-04 01:41
Dupe of #153

**Closed by harshavamsi** 2023-04-04 01:41 UTC
Labels: enhancement, untriaged
