### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by evoisec** [opensearch-project/opensearch-hadoop#135] opened 2023-03-06 16:18 UTC
### What is the bug?
lib jar not available 

### How can one reproduce the bug?
lib jar not to be found 

### What is the expected behavior?
lib jar on e.g. Maven Central

### What is your host/environment?
AWS OS

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
Is there officially released / production ready jar (also endorsed by Amazon) or this project is still in early development

**Comment by wbeckler** [comment] 2023-03-09 17:34
This is a dupe of https://github.com/opensearch-project/opensearch-hadoop/issues/134
Read the comment regarding security review for an update on the status of a Maven release.

**Closed by wbeckler** 2023-03-09 17:34 UTC
Labels: bug, untriaged
